name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: sparkles
          POSTGRES_PASSWORD: sparkles
          POSTGRES_DB: sparkles_test
        ports:
          - 5432:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    env:
      RAILS_ENV: test
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: sparkles
      DATABASE_PASSWORD: sparkles

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Prepare test database
        run: |
          bin/rails db:prepare

      - name: Compile JavaScript packs
        env:
          NODE_ENV: test
        run: |
          bin/rails webpacker:install
          bin/rails webpacker:compile

      - name: Run tests
        run: |
          bin/rspec
